import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/NavigationBar/NavigationBar";
import { ClerkProvider} from '@clerk/nextjs'
import { ThemeProvider } from "@/components/ui/theme-provider"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Code Ascend",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} dark:bg-gradient-to-b from-gray-950 to-black antialiased`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="light" 
            enableSystem={false}
            disableTransitionOnChange
          >
            <NavigationBar/>
            {children}
          </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
