export default function Topics(){
    const topics = [
        { name: "Array", problemsCount: 1798 },
        { name: "String", problemsCount: 749 },
        { name: "Hash Table", problemsCount: 652 },
        { name: "Dynamic Programming", problemsCount: 554 },
        { name: "Math", problemsCount: 544 },
        { name: "Sorting", problemsCount: 424 },
        { name: "Greedy", problemsCount: 391 },
        { name: "Depth-First Search", problemsCount: 307 },
        { name: "Database", problemsCount: 293 },
        { name: "Binary Search", problemsCount: 290 },
        { name: "Matrix", problemsCount: 241 },
        { name: "Tree", problemsCount: 239 },
        { name: "Breadth-First Search", problemsCount: 237 },
        { name: "Bit Manipulation", problemsCount: 230 },
        { name: "Two Pointers", problemsCount: 210 },
        { name: "Prefix Sum", problemsCount: 184 },
        { name: "Heap (Priority Queue)", problemsCount: 182 },
        { name: "Binary Tree", problemsCount: 176 },
        { name: "Simulation", problemsCount: 167 },
        { name: "Stack", problemsCount: 164 },
        { name: "Graph", problemsCount: 156 },
        { name: "Counting", problemsCount: 154 },
        { name: "Sliding Window", problemsCount: 139 },
        { name: "Design", problemsCount: 126 },
        { name: "Backtracking", problemsCount: 106 },
        { name: "Enumeration", problemsCount: 98 },
        { name: "Union Find", problemsCount: 85 },
        { name: "Linked List", problemsCount: 79 },
        { name: "Ordered Set", problemsCount: 65 },
        { name: "Number Theory", problemsCount: 65 },
        { name: "Monotonic Stack", problemsCount: 63 },
        { name: "Trie", problemsCount: 54 },
        { name: "Segment Tree", problemsCount: 53 },
        { name: "Bitmask", problemsCount: 48 },
        { name: "Queue", problemsCount: 47 },
        { name: "Divide and Conquer", problemsCount: 47 },
        { name: "Recursion", problemsCount: 46 },
        { name: "Combinatorics", problemsCount: 44 },
        { name: "Binary Indexed Tree", problemsCount: 41 },
        { name: "Geometry", problemsCount: 40 },
        { name: "Binary Search Tree", problemsCount: 40 },
        { name: "Hash Function", problemsCount: 39 },
        { name: "Memoization", problemsCount: 39 },
        { name: "String Matching", problemsCount: 33 },
        { name: "Topological Sort", problemsCount: 33 },
        { name: "Shortest Path", problemsCount: 32 },
        { name: "Rolling Hash", problemsCount: 30 },
        { name: "Game Theory", problemsCount: 28 },
        { name: "Interactive", problemsCount: 23 },
        { name: "Data Stream", problemsCount: 21 },
        { name: "Monotonic Queue", problemsCount: 17 },
        { name: "Brainteaser", problemsCount: 17 },
        { name: "Randomized", problemsCount: 12 },
        { name: "Merge Sort", problemsCount: 12 },
        { name: "Doubly-Linked List", problemsCount: 11 },
        { name: "Counting Sort", problemsCount: 9 },
        { name: "Iterator", problemsCount: 9 },
        { name: "Concurrency", problemsCount: 9 },
        { name: "Probability and Statistics", problemsCount: 7 },
        { name: "Quickselect", problemsCount: 7 },
        { name: "Suffix Array", problemsCount: 7 },
        { name: "Bucket Sort", problemsCount: 6 },
        { name: "Minimum Spanning Tree", problemsCount: 5 },
        { name: "Shell", problemsCount: 4 },
        { name: "Line Sweep", problemsCount: 4 },
        { name: "Reservoir Sampling", problemsCount: 4 },
        { name: "Strongly Connected Component", problemsCount: 3 },
        { name: "Eulerian Circuit", problemsCount: 3 },
        { name: "Radix Sort", problemsCount: 3 },
        { name: "Rejection Sampling", problemsCount: 2 },
        { name: "Biconnected Component", problemsCount: 1 },
      ];
    return (
        <div className="flex space-x-4 overflow-hidden w-full mt-4">
            {topics.map((topic,index)=>(
              <p className="text-nowrap" key={index}>{topic.name} <span className="bg-gray-600 p-1 rounded-full text-gray-100 text-[12px]">{topic.problemsCount}</span></p>
            ))}
          </div>
    );
}